### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by datptolemei** [maoxs2/GxMiner#6]
When I compile by myself I have this error when start miner:

```
03:51:16 Pool: pool.supportxmr.com:80
03:51:16 Init Job: ID: 0 Target: 14F8B588E368F Seed: 441D0DDDB06B607E
03:51:16 Dataset initializing
03:51:21 Dataset initialization finished, start mining
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xc8 pc=0x6ddcee]

goroutine 37 [running, locked to thread]:
github.com/maoxs2/gxminer/go-hwloc.(*Topology).HwlocGetNUMANodeObjByOSIndex(0xc0002a4008, 0x1, 0x0)
        E:/gxminer/go-hwloc/mem_windows.go:37 +0x5e
github.com/maoxs2/gxminer/worker.(*Worker).CStart.func1(0xc0002a8140, 0xc0002aa0a0)
        E:/gxminer/worker/worker.go:150 +0xa5
created by github.com/maoxs2/gxminer/worker.(*Worker).CStart
        E:/gxminer/worker/worker.go:147 +0x93
```
But everything is good with precompiled binary from "Release" page.
How can I fix this issue?

**Comment by datptolemei** [comment]
~~this erros is fixed but now miner can't work on all threads, when I put all threads in conf file, working only 2. As in the previus issue binary from "Release page" working on all threads.
Sorry for bad English.~~

Fixed for me when I downgrade Golang version to 1.13.4
